- name: Update apt cache
  apt: update_cache=yes

- name: Install developer packages
  apt: name={{ item }} state=present
  with_items:
  - python3
  - python3-pip
  - picocom
  - git
  - python3-venv
  - cmake
  - libglib2.0-dev
  - libcairo2-dev
  - python3-gi
  - python3-gi-cairo
  - gir1.2-gtk-3.0
  - libgirepository1.0-dev
